web/router.ex
defmodule ChurchWebsite.Router do
  use ChurchWebsite.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChurchWebsite do
    pipe_through :browser # Use the default browser stack

    get     "/",        HomeController,     :index

    get     "/login",   SessionController,  :new
    post    "/login",   SessionController,  :login
    delete  "/logout",  SessionController,  :delete
    get     "/change_password", SessionController, :display_reset_password
    post    "/change_password", SessionController, :reset_password

    get     "/register",RegisterController, :new
    post    "/register",RegisterController, :create


    get "/hello", HelloController, :index
    get "/hello/:messenger", HelloController, :show

    get "/prayer_requests", RequestController, :users_view
    get "/permissions/:input", RequestController, :permissions
    get "/permissions",     RequestController, :show_permissions


    get "/about",   PageController, :about
    get "/history", PageController, :history
    get "/pastor",  PageController, :pastor
    get "/pastor_assistant",    PageController,     :pastor_assistant
    get "/contact",             PageController,     :contact
    get "/ministries/children", PageController,     :children
    get "/ministries/teens",    PageController,     :teens
    get "/ministries/adults",   PageController,     :adults

    get "/user/show", UserController, :show
    #get "/user/edit", UserController, :edit
#    get "/admin/edit", UserController, :admin_edit

    get "/users/all", UserController, :index;

    resources "/users", UserController
    resources "/requests", RequestController
    resources "/notifications", NotificationsController


  end

  # Other scopes may use custom stacks.
  # scope "/api", ChurchWebsite do
  #   pipe_through :api
  # end
end

web/models/user.ex
import Joken
defmodule ChurchWebsite.User do
  use ChurchWebsite.Web, :model

  schema "users" do
    field :name, :string
    field :password, :string, virtual: true
    field :email, :string
    field :lastname, :string
    field :permissions, :string
    field :password_hash, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :lastname ,:password, :permissions, :email])
    |> validate_required([:name, :lastname, :email,]) # email is optional
    |> validate_length(:password, min: 6)
    |> validate_length(:name, min: 2)
    |> validate_length(:lastname, min: 2)
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
    |> hash_password
  end

  defp hash_password(changeset) do
    if password = get_change(changeset, :password) do
      changeset
      |> put_change(:password_hash, Comeonin.Bcrypt.hashpwsalt(password))
    else
      changeset
    end
  end

  def generate_token(user) do
    %{user_id: user.id}
    |> token
    |> with_signer(hs256("secret-change-me"))
    |> sign
    |> get_compact
  end


end

web/controllers/user_controller.ex
defmodule ChurchWebsite.UserController do
  use ChurchWebsite.Web, :controller

  alias ChurchWebsite.User

  def index(conn, _params) do
    if ChurchWebsite.Session.is_admin(conn) do
        users = Repo.all(User)
        render(conn, "index.html", users: users)
    else
        conn |> redirect(to: home_path(conn, :index))
    end

  end


  def show(conn, _params) do
    #user = Repo.get!(User, id)
    user = ChurchWebsite.Session.current_user(conn)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{ "id" => id}= _params) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do

    user = Repo.get!(User,id)
    changeset = User.changeset(user, user_params)
    %{"password" => password} = user_params

    case String.length(password) do
        0 -> update_repo(conn,user,changeset)
        _ -> update_repo(conn,user, change_password(changeset,ChurchWebsite.Repo) )
    end


  end

  import Ecto.Changeset, only: [put_change: 3]
  def change_password(changeset, repo) do
      changeset |> put_change(:password_hash, Comeonin.Bcrypt.hashpwsalt(changeset.params["password"]))
  end

  def update_repo(conn,user,changeset) do

     case Repo.update(changeset) do
         {:ok, _} ->
           if ChurchWebsite.Session.is_admin(conn) do
               conn
               |> put_flash(:info, "User updated successfully.")
               |> redirect(to: user_path(conn, :index))
           else
               conn
               |> put_flash(:info, "User updated successfully.")
               |> redirect(to: user_path(conn, :show))
           end
         {:error, changeset} ->
                render(conn, "edit.html", user: user, changeset: changeset)
       end


   end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end

end

web/views/user_view.ex
defmodule ChurchWebsite.UserView do
  use ChurchWebsite.Web, :view
end

web/templates/user/edit.html.eex
<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

web/templates/user/form.html.eex
  <div class="my-container center">
        
      <h2>Edit user</h2>
      <%= form_for @changeset, @action, fn f -> %>
        <%= if @changeset.action do %>
          <div class="alert alert-danger">
            <p>Oops, something went wrong! Please check the errors below.</p>
          </div>
        <% end %>

        <div class="form-group">
          <%= label f, :name, class: "control-label" %>
          <%= text_input f, :name, class: "form-control" %>
          <%= error_tag f, :name %>
        </div>

        <div class="form-group">
          <%= label f, :lastname, class: "control-label" %>
          <%= text_input f, :lastname, class: "form-control" %>
          <%= error_tag f, :lastname %>
        </div>

        <div class="form-group">
          <%= label f, :email, class: "control-label" %>
          <%= text_input f, :email, class: "form-control" %>
          <%= error_tag f, :email %>
        </div>

        <div class="form-group">
          <%= label f, :Change_Password, class: "control-label" %> 
          <%= text_input f, :password, class: "form-control" %>
           (Leave blank if you don't wish to change your password)
          <%= error_tag f, :password %>
        </div>

        <div class="form-group">
          <%= submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>

  </div>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.lastname %></td>
      <td><%= user.email %></td>

      <td class="text-right">
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>

        <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new), class: "btn btn-default btn-xm" %>

web/templates/user/show.html.eex
<div style="margin: auto; width: 80%;">
    <div style="margin-bottom: 100px; font-size: 20px; ">
      <h2>Show user</h2>

      <ul style="list-style-type: none;">

        <li>
          <strong>First Name:</strong>
          <%= @user.name %>
        </li>

        <li>
            <strong>Last Name:</strong>
            <%= @user.lastname %>
          </li>

        <li>
          <strong>Email:</strong>
          <%= @user.email %>
        </li>

      </ul>

      <%= link "Edit", to: user_path(@conn, :edit, @user), class: "btn btn-primary btn-xm" %>
      <%= link "Back", to: home_path(@conn, :index), class: "btn btn-default btn-xm" %>
    </div>



      
      <%= if is_admin(@conn) do %>

      <div >
      <h2>Administer Links:</h2>

        <ul style="list-style-type: none;">
          <li style="margin-bottom: 20px; "><%= link "Manage Users", to: user_path(@conn, :index), class: "btn btn-default btn-xm" %></li>
          <li style="margin-bottom: 20px;" ><%= link "Manage Notifications", to: notifications_path(@conn, :index), class: "btn btn-danger"%></li>

        </ul>
      </div>

      <% end %>

</div>