web/router.ex
defmodule ChurchWebsite.Router do
  use ChurchWebsite.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChurchWebsite do
    pipe_through :browser # Use the default browser stack

    get     "/",        HomeController,     :index

    get     "/login",   SessionController,  :new
    post    "/login",   SessionController,  :login
    delete  "/logout",  SessionController,  :delete
    get     "/change_password", SessionController, :display_reset_password
    post    "/change_password", SessionController, :reset_password

    get     "/register",RegisterController, :new
    post    "/register",RegisterController, :create


    get "/hello", HelloController, :index
    get "/hello/:messenger", HelloController, :show

    get "/prayer_requests", RequestController, :users_view
    get "/permissions/:input", RequestController, :permissions
    get "/permissions",     RequestController, :show_permissions


    get "/about",   PageController, :about
    get "/history", PageController, :history
    get "/pastor",  PageController, :pastor
    get "/pastor_assistant",    PageController,     :pastor_assistant
    get "/contact",             PageController,     :contact
    get "/ministries/children", PageController,     :children
    get "/ministries/teens",    PageController,     :teens
    get "/ministries/adults",   PageController,     :adults

    get "/user/show", UserController, :show
    #get "/user/edit", UserController, :edit
#    get "/admin/edit", UserController, :admin_edit

    get "/users/all", UserController, :index;

    resources "/users", UserController
    resources "/requests", RequestController
    resources "/notifications", NotificationsController


  end

  # Other scopes may use custom stacks.
  # scope "/api", ChurchWebsite do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule ChurchWebsite.LayoutView do
  use ChurchWebsite.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
	<head>
		<link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  		<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  		<script type="text/javascript" src="/js/sweetalert.min.js" ></script>
		<link rel="stylesheet" type="text/css" href="/js/sweetalert.css">
  		<title>Cornerstone Baptist</title>

	</head>

	
	
	<nav class="navigation" style="float: left;">
		<div class="nav-links">

			<div class="title" onclick="location.href='/'; " style="cursor: pointer;">
				Cornerstone <span style="color: #5397ae;">Baptist Church<span>
			</div>

			<div class="links" style="">
				<ul class="topnav" id="myTopnav">
				  <li class="icon">
				    <a href="javascript:void(0);" style="font-size:15px;" onclick="myFunction()">☰</a>
				  </li>
				  <li><a href="/about">About</a></li>
				  <li><a href="/ministries/children">Ministries</a></li>
				  <li><a href="http://www.cornerstone-baptist.org/sermons/">Sermons</a></li>
				 	<%= if logged_in?(@conn) do %>
				  		<%= if access_requests(@conn) do %>
				  			<li><a href="/prayer_requests">Prayer Requests</a></li>
				  		<%= else %>
				  			<li><a href="/permissions">Prayer Requests</a></li>
				  		<% end %>
				  		<li><a href="<%= user_path(@conn, :show) %>">My Account</a></li>
				    <% end %>


				   <%= if logged_in?(@conn) do %>
				   		<div class="mobile-login">
						   	<li> 
						   		<%= link "Logout", class: "btn btn-default btn-xm", to: session_path(@conn, :delete), method: :delete %>
						   	</li>
					   	</div>
				   <%= else %>
					    <div class="mobile-login">
						    <li><%= link "Login",    to: "/login" %></li>
			              	<li><%= link "Register", to: register_path(@conn, :new) %></li>
		              	</div>
	              	<% end %>


				</ul>

			</div>

		</div> <!-- end of nav links -->
		<script type="text/javascript">
				function myFunction() {
				    var x = document.getElementById("myTopnav");
				    if (x.className === "topnav") {
				        x.className += " responsive";
				    } else {
				        x.className = "topnav";
				    }
				}

				function createPopup(){
					
					swal(
							{   
								title: "Under Construction",   
								text: "Sermons are still available on our old website, click 'ok' to view them.",   
								type: "info",   
								showCancelButton: true,   
								closeOnConfirm: true,   
							}, 
								function(){   
									window.location.href = "http://www.cornerstone-baptist.org/sermons/" 

								}
						);

				}

			</script>

		<div class="login-logout">
			<ul class="nav nav-pills ">
	             <%= if logged_in?(@conn) do %>
	              <div class="username">Welcome,
	              	<span><%= current_user(@conn).email %></span>
	              </div>
	              <li class="logout-button" style="float: right;"> <%= link "Logout", class: "btn btn-default btn-xm", to: session_path(@conn, :delete), method: :delete %></li>
	            <% else %>
	              <li><%= link "Login",    to: "/login" %></li>
	              <li><%= link "Register", to: register_path(@conn, :new) %></li>
	            <% end %>
	      </ul>
		</div>

	</nav><!-- end of navigation -->





	<body>
		<section class="module content">

		  <div class="spacer"></div>
		  
		  <div class="my-container">
		  		<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      			<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

				<%= render @view_module, @view_template, assigns %>
		    </div>
		</section>
	</body>





</html>

web/templates/layout/main_page_layout.html.eex
<!DOCTYPE html>
	<head>
		<link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
		<script type="text/javascript" src="/js/sweetalert.min.js" ></script>
		<link rel="stylesheet" type="text/css" href="/js/sweetalert.css">
 		<title>Cornerstone Baptist</title>

	</head>


	<nav class="navigation" style="float: left;">
		<div class="nav-links">

			<div class="title" onclick="location.href='/'; " style="cursor: pointer;">
				Cornerstone <span style="color: #5397ae;">Baptist Church<span>
			</div>

			<div class="links" style="">
				<ul class="topnav" id="myTopnav">
				  <li class="icon">
				    <a href="javascript:void(0);" style="font-size:15px;" onclick="myFunction()">☰</a>
				  </li>
				  <li><a href="/about">About</a></li>
				  <li><a href="/ministries/children">Ministries</a></li>
				  <li><a href="#" onclick="createPopup();">Sermons</a></li>
				 	<%= if logged_in?(@conn) do %>
				  		<%= if access_requests(@conn) do %>
				  			<li><a href="/prayer_requests">Prayer Requests</a></li>
				  		<%= else %>
				  			<li><a href="/permissions">Prayer Requests</a></li>
				  		<% end %>
				  		<li><a href="<%= user_path(@conn, :show) %>">My Account</a></li>
				    <% end %>


				   <%= if logged_in?(@conn) do %>
				   		<div class="mobile-login">
						   	<li> 
						   		<%= link "Logout", class: "btn btn-default btn-xm", to: session_path(@conn, :delete), method: :delete %>
						   	</li>
					   	</div>
				   <%= else %>
					    <div class="mobile-login">
						    <li><%= link "Login",    to: "/login" %></li>
			              	<li><%= link "Register", to: register_path(@conn, :new) %></li>
		              	</div>
	              	<% end %>


				</ul>

			</div>

		</div> <!-- end of nav links -->

		<script type="text/javascript">
			function myFunction() {
			    var x = document.getElementById("myTopnav");
			    if (x.className === "topnav") {
			        x.className += " responsive";
			    } else {
			        x.className = "topnav";
			    }
			}

			function createPopup(){
				
				swal(
						{   
							title: "Under Construction",   
							text: "Sermons are still available on our old website, click 'ok' to view them.",   
							type: "info",   
							showCancelButton: true,   
							closeOnConfirm: true,   
						}, 
							function(){   
								window.location.href = "http://www.cornerstone-baptist.org/sermons/" 

							}
					);

			}

		</script>

		<div class="login-logout">
			<ul class="nav nav-pills ">
	             <%= if logged_in?(@conn) do %>
	              <div class="username">Welcome,
	              	<span><%= current_user(@conn).email %></span>
	              </div>
	              <li class="logout-button" style="float: right;"> <%= link "Logout", class: "btn btn-default btn-xm", to: session_path(@conn, :delete), method: :delete %></li>
	            <% else %>
	              <li><%= link "Login",    to: "/login" %></li>
	              <li><%= link "Register", to: register_path(@conn, :new) %></li>
	            <% end %>
	      </ul>
		</div>

	</nav><!-- end of navigation -->


	<body>
		<%= render @view_module, @view_template, assigns %>
	</body>



	<footer>
        <div>&copy; 2017, Cornerstone Baptist Church</div>
    </footer>


</html>

web/templates/layout/old_app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">



    <title>Hello ChurchWebsite!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
             <%= if logged_in?(@conn) do %>
              <li><%= current_user(@conn).email %></li>
              <li> <%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
            <% else %>
              <li><%= link "Login",    to: "/login" %></li>
              <li><%= link "Register", to: register_path(@conn, :new) %></li>
            <% end %>
          </ul>
            <a><img class="mylogo" src="/images/CClogo.png"></a>
        </nav>
        <a href="/"></a>
      </header>




      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>


      

        <div class="mynav">
        <ul>
          <li class="active"><a href="/">Home</a></li>
          <%= if logged_in?(@conn) do %>
                <li><%= link "Prayer Requests",    to: request_path(@conn, :users_view) %></li>
          <% end %>
          <li><a href="/contact">Contact</a></li>
          <li><a href="/about">About</a></li>
        </ul>
        </div>


      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>